### ISSUE TITLE
If data in different tests can merge together to use

### ISSUE THREAD

**Issue by huangfuxc** [Telecommunication-Telemedia-Assessment/AVT-VQDB-UHD-1#9]
If we can merge data in test1 with test2 and test3 directly to use them? Or do we need to train or validate objective metrics on 4 tests dataset separately?

**Comment by slhck** [comment]
You can merge the data by using the commonly used PVS IDs and generating a "virtual" larger test. A method for doing so is shown in Pitrey, Yohann, et al. "Aligning subjective tests using a low cost common set." Euro ITV. 2011.

Basically, you calculate the average MOS for all the PVS that are common between the tests ("common PVS"). Then, for each test, you calculate a first-order linear model that maps the individual common PVS MOS against the average common PVS MOS. Then you apply that linear model to all the PVS in the respective test to shift the scores.

Note, however, that only tests 2 and 3 share common PVS, as the duration of the sources in test 1 was different from test 2 and 3. So they cannot be directly compared. Test 4 uses different framerates and thus cannot be directly compared either.

Hence, I suggest to train on test 1, test 2+3, and 4 separately.

**Comment by huangfuxc** [comment]
Got it, thanks for your guidance!
